### PR TITLE
Allow disabling using file as input in the rsyslog

### PR DESCRIPTION
**Pull request by sunsongxp**

### CODE REVIEW

**Comment by xuqingfeng** [comment]
That's really weird.

I got `segmentation fault` on dior admin.
```
[wcladmin@vm-lvmh-pcd-eloyalty-admin01 rsyslog.d]$ rsyslogd -N1 -f 00-base.conf
rsyslogd: version 8.24.0, config validation run (level 1), master config 00-base.conf
Segmentation fault

---

[wcladmin@sams-admin rsyslog.d]$ rsyslogd -N1 -f 00-base.conf
rsyslogd: version 8.24.0, config validation run (level 1), master config 00-base.conf
rsyslogd: CONFIG ERROR: there are no active actions configured. Inputs will run, but no output whatsoever is created. [v8.24.0 try http://www.rsyslog.com/e/2103 ]
```

**Comment by sunsongxp** [comment]
This is because although we enabled imfile module:

`$ModLoad imfile`

but we actually do not have any file to monitor. All log are sent from node.

```
2854.116965460:main thread    : Called LogMsg, msg: imfile: no files configured to be monitored - no input will be gathered
Segmentation fault
```

I am not sure if it is because version we deploy for Dior is different from other projects.

But you can enable debug mode by using command: `rsyslogd -dn`

**Comment by xuqingfeng** [comment]
I'm talking about `Segmentation fault` error, it's probably caused by bad hostname - https://github.com/rsyslog/rsyslog/issues/1573#issuecomment-315761705, https://github.com/rsyslog/rsyslog/commit/b737047af6cad49f7ab3e8bf47c8dcf3c9a77221

We can either 1. fix the random hostname(vm-lvmh-pcd-eloyalty-admin01 in our case) 2. upgrade rsyslog to a new version.

And after I updated hostname to dior-admin, no more segmentation fault.

PS. we are using the same version(rsyslogd 8.24.0).

**Comment by sunsongxp** [comment]
@xuqingfeng is right. I am surprised that rsyslogd is able to start even if imfile module is enabled when there is no input file provided.

What I experienced was that the rsyslog was unable to start, the segment fault error msg was immediately followed after the error about imfile. But when I removed the imfile load, it get started.

Then there is no point making this change. I'll withdraw the PR.

**Pull request closed without merging**
